# Generated by Django 4.2.30 on 2026-07-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_visit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='owner_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='owner_phone',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
    ]
