# Generated by Django 4.2.30 on 2026-07-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_pet_owner_name_pet_owner_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='appointment_type',
            field=models.CharField(default='Checkup', max_length=20),
            preserve_default=False,
        ),
    ]
