# Generated by Django 4.2.30 on 2026-07-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_pet_appointment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='doctor',
            field=models.CharField(default='Dr. Omar', max_length=100),
            preserve_default=False,
        ),
    ]
