# Generated by Django 4.2.30 on 2026-07-17 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_pet_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='appointment_time',
            field=models.TimeField(default=datetime.time(10, 0)),
            preserve_default=False,
        ),
    ]
