# Generated by Django 4.2.30 on 2026-07-29 00:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_pet_appointment_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='age',
        ),
        migrations.AddField(
            model_name='pet',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2020, 1, 1)),
            preserve_default=False,
        ),
    ]
