# Generated by Django 4.2.30 on 2026-07-29 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_remove_pet_age_pet_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='priority',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent'), ('Emergency', 'Emergency')], default='Normal', max_length=20),
        ),
        migrations.AddField(
            model_name='pet',
            name='visit_reason',
            field=models.CharField(default=datetime.date(2020, 1, 1), max_length=200),
            preserve_default=False,
        ),
    ]
