# Generated by Django 4.2.30 on 2026-07-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_pet_priority_pet_visit_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='visit_date',
        ),
        migrations.AlterField(
            model_name='pet',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='visit_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
