# Generated by Django 4.2.30 on 2026-07-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_remove_pet_visit_date_alter_pet_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
