# Generated by Django 4.2.30 on 2026-07-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0010_pet_visit_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_appointments_per_day', models.PositiveIntegerField(default=3)),
            ],
        ),
    ]
