# Generated by Django 4.2.30 on 2026-07-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0013_editrequest_edit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editrequest',
            name='edit_type',
            field=models.CharField(choices=[('', 'Select Edit Type'), ('Appointment Date', 'Appointment Date'), ('Appointment Time', 'Appointment Time'), ('Doctor', 'Doctor'), ('Visit Reason', 'Visit Reason'), ('Owner Phone', 'Owner Phone'), ('Pet Name', 'Pet Name'), ('Priority', 'Priority'), ('Other', 'Other')], default='', max_length=50),
        ),
    ]
