# Generated by Django 4.2.30 on 2026-08-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0014_alter_editrequest_edit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='appointment_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
