# Generated by Django 4.2.30 on 2026-08-05 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0015_pet_appointment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='consultation_time',
            field=models.PositiveIntegerField(default=30, help_text='Consultation time in minutes'),
        ),
    ]
