# Generated by Django 4.2.30 on 2026-08-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0016_doctor_consultation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Arrived', 'Arrived'), ('Cancelled', 'Cancelled')], default='Waiting', max_length=20),
        ),
    ]
