# Generated by Django 4.2.30 on 2026-08-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0017_pet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='editrequest',
            name='new_appointment_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='editrequest',
            name='new_doctor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='editrequest',
            name='new_owner_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='editrequest',
            name='new_visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='editrequest',
            name='new_visit_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
