# Generated by Django 4.2.30 on 2026-08-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0018_editrequest_new_appointment_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editrequest',
            name='new_pet_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
