# Generated by Django 4.2.30 on 2026-08-08 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0019_editrequest_new_pet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='editrequest',
            name='new_priority',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Urgent', 'Urgent'), ('Emergency', 'Emergency')], max_length=20, null=True),
        ),
    ]
