# Generated by Django 4.2.30 on 2026-08-08 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0022_doctor_user_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='editrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edit_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
